### ISSUE TITLE
Introduce eIAM

### ISSUE THREAD

**Issue by traffic1000** [geoadmin/web-asset-swissgeol#7]
Analogue to Boreholes: use eIAM => Kick-Off with GeoW

- Asset has its own user administration
- Get rid of Go-Through?
- 2-step process for on-boarding of new users (Cognito)
- Roles only in Assets-DB
- JWT

=> time-boxed story: Define stories for next sprint (prio P0)
**latest: Mitte April 2024**

Documentation: https://ebpgroup.atlassian.net/wiki/spaces/223443/pages/2025455619/Auth+Concept+Assets

**Comment by TIL-EBP** [comment]
Nils, 05.04
Hallo Alex und Till

Die Apps im ngm-prod und ngm-int Benutzerpool sind erstellt. Könntest du mir kru Bescheid geben, ob die Konfiguration so in Ordnung ist.

Bezüglich ngm-dev App-Integration ist die Frage gekommen, ob die bestehende App gelöscht und dann die neue erstellt werden kann. Oder musss die momentane App mit den Secrets bestehen bleiben?

Danke und schöne Grüsse

Nils

**Comment by mPfifi** [comment]
eIAM funktioniert bei mir auf INT.
Allerdings habe ich neu nur noch Viewer- statt Admin-Rechte... - sonst aber ok!
